name: transport_app
description: A new Flutter project for JAYA FREIGHT.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider:

  firebase_core:
  firebase_auth:
  cloud_firestore:

  # --- MAPS ---
  google_maps_flutter: ^2.6.0
  google_place: ^0.4.7
  location: ^5.0.3
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
